services:
  postgres:
    image: postgres:17-alpine
    container_name: req_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 10s

  requests_service:
    build:
      dockerfile: Dockerfile
    container_name: req_service
    restart: always
    expose:
      - "8002"
    env_file:
      - docker_build/.env
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker_build/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - requests_service